#!/bin/sh -ex

while [ $# -gt 0 ]; do
	input="$1"
	base="${1%.*}"
	suffix="${1##*.}"
	trf="${base}.trf"
	stable="${base}-stable.${suffix}"

	ffmpeg -i "$input" -vf vidstabdetect=shakiness=10:accuracy=15:stepsize=32:result="$trf" -f null -
	ffmpeg -i "$input" -vf vidstabtransform=input="$trf":zoom=0:smoothing=10,unsharp=5:5:0.8:3:3:0.4 -preset slow -tune film -crf 16 -acodec copy -map_metadata 0 "$stable"
	touch "--reference=$input" "$stable"
	rm "${trf}"
	shift
done
